### ISSUE TITLE
Can't use the tool, dies with SIGSEGV

### ISSUE THREAD

**Issue by bra-fsn** [joboscribe/s3grep#2]
When trying to use this tool, I get:

```
/root/go/bin/s3grep "Taking the poison pill" logs ".*log" us-west-2
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x8a709a]

goroutine 1 [running]:
github.com/joboscribe/s3grep/tool.(*Instance).GetKeys(0xc000349e40, 0x4, 0x4)
	/root/go/src/github.com/joboscribe/s3grep/tool/run.go:94 +0x20a
github.com/joboscribe/s3grep/cli.Run(0xc0000ba010, 0x4, 0x4, 0xc00009c058)
	/root/go/src/github.com/joboscribe/s3grep/cli/run.go:19 +0xa7
main.main()
	/root/go/src/github.com/joboscribe/s3grep/main.go:10 +0x64
```

go version:
`go version go1.13.8 linux/amd64`
The OS is Ubuntu 20.04.3 LTS.

**Comment by joboscribe** [comment]
Thanks for the bug report, @bra-fsn. 

Interesting case given that, as far as i understand the s3 API, if we have `IsTruncated` as `true` in the result object then there should be a valid `ContinuationToken`, but obviously that's not the case. Feels overly cautious to also check for a non-nil `ContinuationToken` but since it's a pointer that's probably what we need to do. I'll get on it.
